# Site settings
title: RIKO & Contagious Records
email: djriko@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
    Riko born and bread from Telford, started out in the Hardcore scene way back in 2008 as 'MC RIKO' with over the years playing a regular show on Midlands Rush 92.2FM, playing for big names like HTID, HTID IN THE SUN, RAVERS REUNITED, RAVER BABY, TOTALLY LOST IT, B2T + many more.. Riko felt he needed a change, a different direction as a artist..
    
    2012/2013 Riko hung up the mic to become DJ RIKO.. Years after Riko still felt something was missing.. So he decided to stop DJ'ing and teach himself how to make his very own tracks and create his very own style..
    
    2014 Riko created his very own label Contagious Records and has continued to release his own music along with fresh and exciting up and comers to this day

baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
url: "http://localhost:8000" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
