# Site settings
title: RIKO & Contagious Records
email: djriko@hotmail.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://djriko.co.uk" # the base hostname & protocol for your site
twitter_username: danbennett
github_username: danbennettuk

# Build settings
markdown: kramdown
permalink: pretty
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
